config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'index_show'
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :categories, only: :show
  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
.like-link{:id => "like-link-#{post.id}"}
  - if current_user.likes.find_by(post_id: post.id)
    = link_to unlike_path(post.id), method: :delete, remote: true do
      .iine__button
        %i.fas.fa-heart.heart_red  
  - else
    = link_to like_path(post.id), method: :post, remote: true do
      .iine__button
        %i.far.fa-heart

app/views/likes/like.js.haml
$("#{@id_name}").html('#{escape_javascript(render("likes/like", post: @post  ))}');

app/views/likes/unlike.js.haml
$("#{@id_name}").html('#{escape_javascript(render("likes/like", post: @post  ))}');