config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'index_show'
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :categories, only: :show
  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  mount_uploader :image, ImageUploader

  validates :nickname, length: { maximum: 20 }, presence: true
  validates :introduction, length: { maximum: 200 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   render layout: 'ファイル名’ 
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @posts = @user.posts.includes([:user, :images]).order("created_at DESC")
    @parents = Category.all.order("id ASC").limit(25)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render :update
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:image, :nickname, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.edit-container
  = render "devise/shared/error_messages", resource: @user
  = form_with(model: @user, local: true) do |form|
    .containers
      %h3.title
        編集する
      %br
      .image-form
        = form.label :image, class: 'image_label' do
          .prev-contents
            - if current_user.image.present?
              .prev-content
                = image_tag current_user.image.url, alt: "preview", class: "prev-image"
            - else
              = icon('fas', 'user', class: 'photo-icon')
          = form.file_field :image, class: 'image_form__contents__field hidden_file'
      .introduction-form
        %h1.nickname ニックネーム(必須)
        %p.nickname-form
          = form.text_field :nickname, placeholder: "20文字まで"
        %br
        %h1.intro 紹介文(任意)
        %p.intro-form
          = form.text_area :introduction, placeholder: "200文字まで"
        %br
        .introduction-submit
          %p.submit
            = form.submit "SEND"

app/views/users/show.html.haml
.contents_user_show

  .user-information
    .user-image
      %img.user-icon{src: @user.image }
    .user-introduction
      - if user_signed_in? && current_user.id == @user.id
        .user-font
          %a.font__cog
            = link_to destroy_user_session_path, method: :delete do
              %i.fas.fa-sign-out-alt
          %a.font__edit
            = link_to edit_user_path do
              %i.fas.fa-cog
          %a.font__cog
            = link_to new_post_path do
              %i.fas.fa-edit
      %p.text
        = @user.nickname
      .introduction
        %p.content
          = @user.introduction
      .counting
        %p.post-count
          投稿数
          = @posts.count
        %p.likes-count
          総いいね数
          = @posts.all.sum(:likes_count)
  %p.look
    = @nickname
    さんの投稿一覧
    .main-posts-detail
      - @posts.each do |post|
        =link_to "/posts/#{post.id}" ,class: "posts-show" do
          .detail-image{style: "background-image: url(#{post.images.first.src.url});"}
          .mask
            .likes
              ♡
              = post.likes_count
            .text
              - @parents.each do |parent|
                - if post.category_id == parent.id
                  = parent.name 

app/views/users/update.html.haml
.contents__row
  .success
    %h3
      編集が完了しました。
    %a.btn{href: "/posts"} 投稿一覧へ戻る