config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'index_show'
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :categories, only: :show
  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  belongs_to :category, optional: true
  accepts_nested_attributes_for :images, allow_destroy: true

  def self.search(search)
    return Post.all unless search
    Post.where('text LIKE(?)', "%#{search}%")
  end

  accepts_nested_attributes_for :images, allow_destroy: true
  validates :text, length: { maximum: 50 }, presence: true
  validates :content, length: { maximum: 500 }
  validates :category_id, :images, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes([:user ,:images]).order("created_at DESC").page(params[:page]).per(12)
    @post_topics = Post.includes(:category).order("created_at DESC").page(params[:page]).per(4)
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
    @parents = Category.all.order("id ASC").limit(25)
    @post_food = Post.where(category_id: 5).order("created_at DESC").page(params[:page]).per(4)
    @post_fashion = Post.where(category_id: 3).order("created_at DESC").page(params[:page]).per(4)
    @top_ranks = Post.includes(:user).find(Like.group(:post_id).pluck(:post_id))
    @my_ranks = @all_ranks.select{ |post| post.category_id == 3 }
  end

  def category
  end

  def new
    @post = Post.new
    @post.images.new
    @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("選択してください")
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

 # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render :create
    else
      @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("選択して下さい")
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
  end

  def show
    post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end
  
  def search
    @posts = Post.search(params[:keyword])
    @parents = Category.all.order("id ASC").limit(25)
  end

  def index_show
    @posts = Post.includes([:user ,:images]).order("created_at DESC").page(params[:page]).per(50)
    @parents = Category.all.order("id ASC").limit(25)
  end

  private
  def post_params
    params.require(:post).permit(:image, :text, :content, :category_id, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
  
end

app/views/posts/_main_posts.html.haml
.main-posts
  .main-posts__post
    .post-title
      %ul.title
        %li.subtitle
          Posts
        %li.mini
          %p
            ポスト
        %li

    - @posts.each do |post|
      .main-posts__post__detail
        %ul.main-posts__post__detail__more
          %li.nickname
            =link_to "#{post.user.nickname}","/users/#{post.user.id}"
          %li.text
            %p さんのポスト
        .main-posts__post__detail__image{:style => "background-image: url(#{post.images.first.src.url});"}
        .more-contents
          =link_to "#{post.text}","/posts/#{post.id}"
          %ul.like-create-tags
            %li.like
              %p.likes-count
                ♡
                =post.likes_count
            %li.create
              %p(datetime="#{post.created_at}")= time_ago_in_words(post.created_at)
            %li.tags
              - @parents.each do |parent|
                - if post.category_id == parent.id
                  .bar-thery
                    = link_to "categories/#{post.category.id}", class:"thery-field", id: "bar-d" do
                      = parent.name 
    .mainposts__post__detail__more
      .more-link
        =link_to index_show_posts_path , class: "morelink-btn" do
          %p.more-text
            もっと見る
  
  .main-posts__side-bar
    .main-posts__side-bar__user
      %img.main-posts__side-bar__user__icon{src: current_user.image }
      .main-posts__side-bar__user__myuser
        %span.main-posts__side-bar__user__myuser__text
          = current_user.nickname
      .main-posts__side-bar__user__font
        %a.font__edit
          = link_to "/users/#{current_user.id}" do
            %i.fas.fa-user
        %a.font__cog
          = link_to destroy_user_session_path, method: :delete do
            %i.fas.fa-sign-out-alt
        %a.font__edit
          = link_to "users/edit" do
            %i.fas.fa-cog
        %a.font__cog
          = link_to "posts/new" do
            %i.fas.fa-edit
    
    .main-posts__side-bar__rank
      %h2.title
        Ranking

    .main-posts__side-bar__posts
      - @all_ranks.each.with_index(1) do |post, i|
        .main-posts__side-bar__posts__post
          .main-posts__side-bar__posts__post__like
            ♡
            =post.likes_count
          .main-posts__side-bar__posts__post__image{:style => "background-image: url(#{post.images.first.src.url});"}
          .main-posts__side-bar__posts__post__text=link_to "#{post.text}","/posts/#{post.id}"

    .main-posts__side-bar__collections
      - @my_ranks.first(1).each do |post|
        =link_to "/posts/#{post.id}", {class: "collection"} do
          .title
            %h2.subtitle
              BestFashion
            %p.user-name
              = post.user.nickname
          .snap{:style => "background-image: url(#{post.images.first.src.url});"}

app/views/posts/_posts_topics.html.haml
%section.top-view__pickup
  %h2.head
    Topics
  .products
    .products__head
      = link_to "categories/5" do
        %h3.title
          グルメ

    .products__lists
      - @post_food.each do |post|
        .list
          = link_to "/posts/#{post.id}" do
            %figure.list-img{:style => "background-image: url(#{post.images.first.src.url});"}
              .post-text
                %p.text
                  =post.text

%section.top-view__pickup
  %h2.head
    Topics
  .products
    .products__head
      = link_to "categories/3" do
        %h3.title
          Fashion

    .products__lists
      - @post_fashion.each do |post|
        .list
          = link_to "/posts/#{post.id}" do
            %figure.list-img{:style => "background-image: url(#{post.images.first.src.url});"}
              .post-text
                %p.text
                  =post.text

app/views/posts/_slick_posts.html.haml
.slick-contents
  %div.slick
    - @posts.first(4).each do |post|
      .posts
        =link_to "/posts/#{post.id}", class: "posts-show" do
          %img.image{src: post.images.first.src.url }
          .mask
            .likes
              ♡
              = post.likes_count
            .text
              - @parents.each do |parent|
                - if post.category_id == parent.id
                  = parent.name 

app/views/posts/create.html.haml
.contents__row
  .success
    %h3
      投稿が完了しました。
    %a.btn{:href => "/posts"} 投稿一覧へ戻る

app/views/posts/destroy.html.haml
.contents__row
  .success
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/posts/edit.html.haml
.container
  = form_with(model: @post, local: true) do |form|
    %h3
      する
    %br
    %ul
      %h1 image URL
      %li= form.text_field :image, placeholder: "Image Url"
      %br
      %h1 title
      %li= form.text_area :text, placeholder: "text"
      %br
      %h1 contents
      %li= form.text_area :content, placeholder: "content" , rows: "10"
      %li= form.submit "SEND"

app/views/posts/index.html.haml
.wrapper
  = render "slick_posts"
  = render "main_posts"
  = render "posts_topics"

app/views/posts/index_show.html.haml
.contents_user_show
  %p.category-name
    新規投稿一覧
    .main-posts-detail
      - @posts.each do |post|
        =link_to "/posts/#{post.id}" ,class: "posts-show" do
          .detail-image{style: "background-image: url(#{post.images.first.src.url});"}
          .mask
            .likes
              ♡
              = post.likes_count
            .text
              - @parents.each do |parent|
                - if post.category_id == parent.id
                  = parent.name

app/views/posts/new.html.haml
.new-container
  = form_with model: @post, local: true do |form|
    .containers
      = render "devise/shared/error_messages", resource: @post
      %h3.title
        投稿する
      %br
      %ul
        %h1.top タイトル(必須)
        %li.top-form
          = form.text_field :text, placeholder: "50文字以内"
        %br
        %li
          .sale-image
            .sale-image__form
              %p.max-uploads
                最大4枚までアップロードできます
              .post__drop__box__container
                .prev-content
                .label-content
                  = form.label :"images_attributes_#{@post.images.count}_src", class: "label-box", id: "label-box--#{@post.images.count}" do
                    %pre.label-box__text-visible クリックしてファイルをアップロード
                .hidden-content
                  = form.fields_for :images do |i|
                    = i.file_field :src, class: "hidden-field"
                    %input{name: "post[images_attributes][0][_destroy]", id: "post_images_attributes_0__destroy", class:"hidden-checkbox", type:"checkbox", value:"0"}
                  - @post.images.length.upto(3) do |i|
                    %input{name: "post[images_attributes][#{i}][src]", id: "post_images_attributes_#{i}_src", class:"hidden-field", type:"file"}
                    %input{name: "post[images_attributes][#{i}][_destroy]", id: "post_images_attributes_#{i}__destroy", class:"hidden-checkbox", type:"checkbox", value:"#{i}"}
        %br
        %h1.bottom 本文(任意)
        %li.bottom-form
          = form.text_area :content, placeholder: "500文字以内" , rows: "10"
        %br

        %li.listing-form-box
          .listing-product-detail__category
            %h1.category カテゴリ(必須)
            .listing-select-wrapper
              .listing-select-wrapper__box
                = form.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
          .submit-btn
            = form.submit "SEND"
    

app/views/posts/search.html.haml
.contents_user_show
  %p.category-name
    -# = @category.name
    の投稿一覧
    .main-posts-detail
      - @posts.each do |post|
        =link_to "/posts/#{post.id}" ,class: "posts-show" do
          .detail-image{style: "background-image: url(#{post.images.first.src.url});"}
          .mask
            .likes
              ♡
              = post.likes_count
            .text
              - @parents.each do |parent|
                - if post.category_id == parent.id
                  = parent.name

app/views/posts/show.html.haml
.post_show
  .post_show--title
    .slick-contents-show
      %div.slick-show
        - @post.images.first(1).each do |image|
          = image_tag image.src.url, class: 'top-image'
          - @post.images[1..3].each do |image|
            = image_tag image.src.url, class: 'sub-image' 
    .contents_post_show
      .contents_post__text
        = @post.text
      .contents_post__content
        =simple_format @post.content
      .like-edit-comment
        = render 'likes/like', post: @post
      .contents_post__comments
        - if @comments
          - @comments.each do |comment|
            .inner-contents
              %img.comments-image{src: comment.user.image }
              = link_to comment.user.nickname, "/users/#{comment.user_id}" 
              %p.text
                = comment.text
              %p.created_at
                = time_ago_in_words(comment.created_at)
      .contents_post__comment
        -if current_user
          = form_with(model: [@post, @comment], local: true) do |form|
            = form.text_area :text, placeholder: "コメントする", rows: "2"
            .submit
              = form.submit "SEND"
      =link_to "/users/#{@post.user.id}", class: "contents_post__image" do
        .image-outline
          %img.image{src: @post.user.image }
      -if user_signed_in? && current_user.id == @post.user_id
        .charm__icon
          = link_to "/posts/#{@post.id}", method: :delete do
            %i.far.fa-trash-alt

app/views/posts/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る