config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'index_show'
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :categories, only: :show
  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  belongs_to :category, optional: true
  accepts_nested_attributes_for :images, allow_destroy: true

  def self.search(search)
    return Post.all unless search
    Post.where('text LIKE(?)', "%#{search}%")
  end

  accepts_nested_attributes_for :images, allow_destroy: true
  validates :text, length: { maximum: 50 }, presence: true
  validates :content, length: { maximum: 500 }
  validates :category_id, :images, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  mount_uploader :image, ImageUploader

  validates :nickname, length: { maximum: 20 }, presence: true
  validates :introduction, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
  end

  def layout_by_resource
    if devise_controller?
      "sub"
    else
      "application"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @category_posts = @category.posts.order("created_at DESC").page(params[:page]).per(4)
    @parents = Category.all.order("id ASC").limit(25)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes([:user ,:images]).order("created_at DESC").page(params[:page]).per(12)
    @post_topics = Post.includes(:category).order("created_at DESC").page(params[:page]).per(4)
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
    @parents = Category.all.order("id ASC").limit(25)
    @post_food = Post.where(category_id: 5).order("created_at DESC").page(params[:page]).per(4)
    @post_fashion = Post.where(category_id: 3).order("created_at DESC").page(params[:page]).per(4)
    @top_ranks = Post.includes(:user).find(Like.group(:post_id).pluck(:post_id))
    @my_ranks = @all_ranks.select{ |post| post.category_id == 3 }
  end

  def category
  end

  def new
    @post = Post.new
    @post.images.new
    @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("選択してください")
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

 # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render :create
    else
      @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("選択して下さい")
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
  end

  def show
    post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end
  
  def search
    @posts = Post.search(params[:keyword])
    @parents = Category.all.order("id ASC").limit(25)
  end

  def index_show
    @posts = Post.includes([:user ,:images]).order("created_at DESC").page(params[:page]).per(50)
    @parents = Category.all.order("id ASC").limit(25)
  end

  private
  def post_params
    params.require(:post).permit(:image, :text, :content, :category_id, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   render layout: 'ファイル名’ 
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @posts = @user.posts.includes([:user, :images]).order("created_at DESC")
    @parents = Category.all.order("id ASC").limit(25)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render :update
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:image, :nickname, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Fashion Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
  %body
    .top-bar
      .top-bar__serch
        = form_with(url: search_posts_path, local: true, method: :get, class: "search_container") do |form|
          = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
          = form.submit class: "search-btn", value: "👠"

      .top-bar__top
        = link_to root_path do
          %p.top__title 
            Fashion Blog
      -# .category_list
      -#   .parents_list
      -#     - @parents.each do |parent|
      -#       = link_to "#{parent.name}", root_path, class: "parent_category",id: "#{parent.id}"
      -#   .children_list
      -#   .grand_children_list


      %ul.top-bar__charm
        %li.charm__icon1
          = link_to '#' do
            %i.fab.fa-instagram
        %li.charm__icon2
          = link_to '#' do
            %i.fab.fa-facebook-square
        %li.charm__icon3
          = link_to '#' do
            %i.fab.fa-twitter-square
    = yield

    .footer
      %ul.contents
        %li.content
          %h2.content__head
            カテゴリ
          %ul.content__list
            %li
              = link_to "categories/3" do
                ファッション
            %li
              = link_to "categories/4" do
                ビューティ
            %li
              = link_to "categories/5" do
                グルメ
            %li
              = link_to "categories/6" do
                アート
            %li
              = link_to "categories/7" do
                映画
            %li
              = link_to "categories/8" do
                音楽
            %li
              = link_to "categories/9" do
                ライフスタイル・カルチャー
            %li
              = link_to "categories/10" do
                その他

        %li.content
          %h2.content__head
            ジャンル
          %ul.content__list
            %li
              = link_to "categories/12" do
                アイテム
            %li
              = link_to "categories/13" do
                イベント
            %li
              = link_to "categories/14" do
                トピック
            %li
              = link_to "categories/15" do
                ショップ
            %li
              = link_to "categories/16" do
                コレクション
            %li
              = link_to "categories/17" do
                特集
            %li
              = link_to "categories/18" do
                インタビュー
            %li
              = link_to "categories/19" do
                その他

        %li.content
          %h2.content__head
            性別
          %ul.content__list
            %li
              = link_to "categories/21" do
                すべて
            %li
              = link_to "categories/22" do
                ウィメンズ
            %li
              = link_to "categories/23" do
                メンズ
            %li
              = link_to "categories/24" do
                ウィメンズ&メンズ

app/views/layouts/sub.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Postmap
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
  %body
    = yield